version: 2
registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/felleslosninger
    username: ${{secrets.MAVEN_USER}}
    password: ${{secrets.MAVEN_PASSWORD}}
updates:
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    registries:
      - maven-github
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
