name: digital-lommebok-demo
networks:
  demo:
    name: demo


services:
  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      start_period: 3s
      timeout: 2s
      retries: 20
    ports:
      - "9282:6379"
    networks:
      - demo
    command: redis-server --maxmemory-policy allkeys-lru

  eudiw-verifier:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
      args:
        GIT_PACKAGE_TOKEN: ${GIT_PACKAGE_TOKEN}
        GIT_PACKAGE_USERNAME: ${GIT_PACKAGE_USERNAME}
    environment:
      _JAVA_OPTIONS: "-XX:UseSVE=0"
      spring_profiles_active: docker
    env_file:
      - .env
    ports:
      - "8082:8443"
      - "8092:8090"
      - "5062:5006"
    networks:
      - demo
    entrypoint: "/bin/bash -c"
    command:
      - |
        cd /usr/local/tomcat/webapps/
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -jar application.jar
