spring:
  application:
    environment: dev
  config:
    import: file:.env[.properties]
  data:
    redis:
      port: 9282
      host: localhost

vcverifier:
  siop2ClientId: abr.vc.local
  client-identifier-scheme: x509_hash
  externalBaseUrl: http://abr.vc.local:8080
  authorization-request-url-scheme: eudi-openid4vp
#  externalBaseUrl: http://localhost:8080
#  externalBaseUrl: http://10.0.2.2:8080

idporten-key-manager:
  keystores:
    access:
      key-store-type: pkcs12
      key-store-location: base64:${VERIFIER_KEYSTORE}
      key-store-password: changeit
      key-alias: rp-access
      key-password: changeit
