spring:
  application:
    environment: systest
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - digital-lommebok-redis-ha-server-0.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-1.digital-lommebok-redis-ha:26379
          - digital-lommebok-redis-ha-server-2.digital-lommebok-redis-ha:26379

vcverifier:
  siop2ClientId: demo-brukersted.eidas2sandkasse.dev
  client-identifier-scheme: x509_hash
  authorization-request-url-scheme: eudi-openid4vp
  externalBaseUrl: https://demo-brukersted.eidas2sandkasse.dev
