spring:
  application:
    environment: test

vcverifier:
  siop2ClientId: demo-vc-verifier.test.idporten.no
  externalBaseUrl: https://demo-vc-verifier.test.idporten.no
  keystores:
    - type: JKS
      location: base64:${VERIFIER_KEYSTORE}
      password: ${VERIFIER_KEYSTORE_PASSWORD}
      key-alias: ${VERIFIER_KEY_ALIAS}
      key-password: ${VERIFIER_KEY_PASSWORD}
