spring:
  application:
    environment: test

vcverifier:
  siop2ClientId: demo-brukersted.test.eidas2sandkasse.net
  client-identifier-scheme: x509_san_dns
  externalBaseUrl: https://demo-brukersted.test.eidas2sandkasse.net
  keystores:
    - type: pkcs12
      location: ${VERIFIER_KEYSTORE}
      password: ${VERIFIER_KEYSTORE_PASSWORD}
      key-alias: ${VERIFIER_KEY_ALIAS}
      key-password: ${VERIFIER_KEY_PASSWORD}
