spring:
  application:
    environment: systest

vcverifier:
  siop2ClientId: demo-vc-verifier.idporten.dev
  externalBaseUrl: https://demo-vc-verifier.idporten.dev
  keystores:
    - type: JKS
      location: ${VC_VERIFIER_JKS}
      password: ${VERIFIER_STORE_PASSWORD]
      key-alias: ${VERIFIER_KEY_ALIAS]
      key-password: ${VERIFIER_KEY_PASSWORD]
