# local dev profile
spring:
  application:
    environment: docker
server:
  port: 8443
  ssl:
    enabled: true
    protocol: TLS
    key-store-type: JKS
    key-store: classpath:selfsigned.jks
    key-store-password: changeit
    key-alias: tomcat
    key-password: changeit
management:
  server:
    port: 8090

vcverifier:
  siop2ClientId: abr.vc.local
  client-identifier-scheme: x509_san_dns
  externalBaseUrl: https://abr.vc.local:8082
  keystores:
    - type: JKS
      location: base64:${VERIFIER_KEYSTORE}
      password: changeit
      key-alias: verifier
      key-password: changeit
