spring:
  application:
    environment: dev

vcverifier:
  siop2ClientId: abr.vc.local
  externalBaseUrl: http://abr.vc.local:8080
  keystores:
    - type: JKS
      location: base64:${VC_VERIFIER_JKS}
      password: changeit
      key-alias: abr.vc.local
      key-password: changeit
