spring:
  application:
    environment: systest

vcverifier:
  siop2ClientId: eudiw-verifier-demo.idporten.dev
  externalBaseUrl: https://eudiw-verifier-demo.idporten.dev/
  keystores:
    - type: JKS
      location: base64:${VERIFIER_KEYSTORE}
      password: ${VERIFIER_KEYSTORE_PASSWORD}
      key-alias: ${VERIFIER_KEY_ALIAS}
      key-password: ${VERIFIER_KEY_PASSWORD}
