spring:
  application:
    environment: test

vcverifier:
  siop2ClientId: demo-vc-verifier.test.idporten.no
  externalBaseUrl: https://demo-vc-verifier.test.idporten.no
  keystores:
    - type: JKS
      location: ${VC_VERIFIER_JKS}
      password: ${VERIFIER_STORE_PASSWORD]
      key-alias: ${VERIFIER_KEY_ALIAS]
      key-password: ${VERIFIER_KEY_PASSWORD]
