# local dev profile
spring:
  application:
    environment: docker
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8443
  ssl:
    enabled: true
    protocol: TLS
    key-store-type: JKS
    key-store: classpath:selfsigned.jks
    key-store-password: changeit
    key-alias: tomcat
    key-password: changeit
management:
  server:
    port: 8090

vcverifier:
  siop2ClientId: abr.vc.local
  client-identifier-scheme: x509_san_dns
  authorization-request-url-scheme: eudi-openid4vp
  externalBaseUrl: https://abr.vc.local:8082

idporten-key-manager:
  keystores:
    access:
      key-store-type: pkcs12
      key-store-location: base64:${VERIFIER_KEYSTORE}
      key-store-password: changeit
      key-alias: rp-access
      key-password: changeit
