spring:
  application:
    environment: dev
  config:
    import: file:.env[.properties]

vcverifier:
  siop2ClientId: abr.vc.local
  client-identifier-scheme: x509_san_dns
  externalBaseUrl: http://abr.vc.local:8080
  keystores:
    - type: JKS
      location: base64:${VERIFIER_KEYSTORE}
      password: changeit
      key-alias: verifier
      key-password: changeit
